name: BCP
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - scanpy=1.9.8    
  - pandas=2.2.2     
  - seaborn=0.13.2    
  - matplotlib=3.8.4  
  - multiqc=1.21      
  - star=2.7.10b      
