run_modules:
  - custom_content
module_order:
  - custom_content
title: "BCP Single-Cell QC Report"

ignore_images: true          # 关掉自动扫图（防止其它 PNG 混进来）
skip_generalstats: true      # 可选：关总表

# 可选但很稳妥：黑名单掉不想要的两张
fn_ignore:
  - "*_violin_before_mito_filtering_QC1.png"
  - "*_violin_comparison_QC2.png"

custom_data:
  img_scatter_doublet_qc2:
    section_name: "sample1 scatter doublet highlight QC2"
    description: "..."
    file_format: png
    plot_type: image
    fn: "*_scatter_doublet_highlight_QC2.png"   # ← 放这里

  img_umap_leiden_qc2:
    section_name: "sample1 umap leiden QC2"
    description: "..."
    file_format: png
    plot_type: image
    fn: "*_umap_leiden_QC2.png"

  img_marker_genes_heatmap:
    section_name: "a.sample1 marker genes heatmap"   # ← 加了 a.
    description: "..."
    file_format: png
    plot_type: image
    fn: "*_marker_genes_heatmap.png"

custom_content:
  order:
    - img_scatter_doublet_qc2
    - img_umap_leiden_qc2
    - img_marker_genes_heatmap
