# ====================================================================
#          MultiQC Custom Configuration for scRNA-seq QC
# ====================================================================

title: "Single-Cell QC Pipeline Report"


custom_content:
  # Give this custom table a unique ID for easy reference in module_order.
  scanpy_qc_table:
    plot_type: 'table'
    file_format: 'tsv'
    module_name: 'Scanpy QC Statistics'
   #file_patt: "*_qc_metrics.tsv"
    sample_names_first_col: False
    headers:
      cells_after_soupx:
        title: 'Cells (Post-SoupX)'
        description: 'Number of cells remaining after SoupX correction and initial filtering.'
        format: '{:,.0f}'
      predicted_doublets:
        title: 'Predicted Doublets'
        description: 'Number of predicted doublets detected by Scrublet.'
        format: '{:,.0f}'
      cells_after_doublet_removal:
        title: 'Cells (Post-Scrublet)'
        description: 'Number of cells remaining after doublet removal.'
        format: '{:,.0f}'
      median_genes_after_doublet:
        title: 'Median Genes (Post-Scrublet)'
        description: 'Median genes per cell after doublet removal.'
        format: '{:,.0f}'
      median_counts_after_doublet:
        title: 'Median UMIs (Post-Scrublet)'
        description: 'Median UMI counts per cell after doublet removal.'
        format: '{:,.0f}'
      cells_final_qc:
        title: 'Cells (Final)'
        description: 'Final number of cells after all QC steps (including mitochondrial filtering).'
        format: '{:,.0f}'
      median_genes_final_qc:
        title: 'Median Genes (Final)'
        description: 'Final median genes per cell after all QC.'
        format: '{:,.0f}'
      median_counts_final_qc:
        title: 'Median UMIs (Final)'
        description: 'Final median UMI counts per cell after all QC.'
        format: '{:,.0f}'
sp:
  custom_content:
    fn: "*_qc_metrics.tsv"

module_order:
    - star:
        name: 'STAR Alignment' 
        info: 'scRNA-seq alignment statistics from STARsolo.'
    - custom_content:
        name: 'Scanpy QC Statistics'
        contents_id: 'scanpy_qc_table'
        info: 'Cell quality control metrics from Scanpy, Scrublet, and SoupX steps.'
    - multiqc:
        name: 'MultiQC Execution'
        info: 'This summary report was generated by MultiQC.'
