# ====================================================================
#          MultiQC Custom Configuration for scRNA-seq QC
# ====================================================================

title: "Single-Cell QC Pipeline Report"


custom_content:
  cells_metrics:               
    file_format: tsv
    plot_type: table
    section_name: "Cells QC Metrics"
    sample_names_first_col: false
    pconfig:
      sortRows: false           

  counts_metrics:
    file_format: tsv
    plot_type: table
    section_name: "Counts QC Metrics"
    sample_names_first_col: false
    pconfig:
      sortRows: false

  genes_metrics:
    file_format: tsv
    plot_type: table
    section_name: "Genes QC Metrics"
    sample_names_first_col: false
    pconfig:
      sortRows: false
sp:
  cells_metrics:
    fn: "*_cells_metrics.tsv"
  counts_metrics:
    fn: "*_counts_metrics.tsv"
  genes_metrics:
    fn: "*_genes_metrics.tsv"

module_order:
    - star:
        name: 'STAR Alignment' 
        info: 'scRNA-seq alignment statistics from STARsolo.'
    - custom_content|cells_metrics
    - custom_content|counts_metrics
    - custom_content|genes_metrics
