run_modules:
  - custom_content

title: "Single-Cell QC Pipeline Report"

custom_data:
  cells_metrics:
    section_name: "Cells QC Metrics"
    description: "Cell counts at different filtering steps"
    file_format: "tsv"
    plot_type: "table"
    sample_names_first_col: true
    pconfig:
      sortRows: false
  counts_metrics:
    section_name: "Counts QC Metrics"
    description: "Median UMI counts at different filtering steps"
    file_format: "tsv"
    plot_type: "table"
    sample_names_first_col: true
    pconfig:
      sortRows: false
  genes_metrics:
    section_name: "Genes QC Metrics"
    description: "Median genes at different filtering steps"
    file_format: "tsv"
    plot_type: "table"
    sample_names_first_col: true
    pconfig:
      sortRows: false
  sam_qc_plots:
    section_name: "SAM QC Plots"
    description: "QC plots generated during SAM QC"
    file_format: "png"

sp:
  cells_metrics:
    fn: "*_cells_mqc.tsv"
  counts_metrics:
    fn: "*_counts_mqc.tsv"
  genes_metrics:
    fn: "*_genes_mqc.tsv"
  sam_qc_plots:
    fn: "*_mqc.png"

ignore_images: false

custom_content:
  order:
    - cells_metrics
    - counts_metrics
    - genes_metrics
    - sam_qc_plots

module_order:
  - star
  - custom_content
