title: "Single-Cell QC Pipeline Report"

custom_content:
  cells_metrics:
    file_format: tsv
    plot_type: table
    section_name: "Cells QC Metrics"
    sample_names_first_col: true
    pconfig:
      sortRows: false
      id: 'cells_metrics_table'

  counts_metrics:
    file_format: tsv
    plot_type: table
    section_name: "Counts QC Metrics"
    sample_names_first_col: true
    pconfig:
      sortRows: false
      id: 'counts_metrics_table'

  genes_metrics:
    file_format: tsv
    plot_type: table
    section_name: "Genes QC Metrics"
    sample_names_first_col: true
    pconfig:
      sortRows: false
      id: 'genes_metrics_table'

  sam_qc_plots:
    file_format: png
    plot_type: image
    section_name: "SAM QC Plots"


sp:
  cells_metrics:
    fn: "*_cells_metrics.tsv"
  counts_metrics:
    fn: "*_counts_metrics.tsv"
  genes_metrics:
    fn: "*_genes_metrics.tsv"
  sam_qc_plots:
    fn: "*.png"

module_order:
  - star
  - custom_content
